//! The committed generated files, and the two checks that keep them honest.
//!
//! # What a golden test does *not* catch
//!
//! Worth stating plainly, because it is the trap this whole increment is shaped
//! around: a golden test proves the emitter still emits **what it emitted
//! before**. It does not prove the output is correct. If the emitter minted
//! `'editr.zoom'` on its first run, the golden would record the typo and every
//! run afterwards would agree with it, forever. Three emitters each agreeing
//! with their own goldens proves nothing at all about whether they agree with
//! each other or with the host.
//!
//! So the goldens are one check among several, and deliberately not the load-
//! bearing one:
//!
//! | Check | Where | What it catches that a golden cannot |
//! |---|---|---|
//! | Paths resolved on a real store | `tests/real_host.rs` | a path literal that addresses nothing, or the wrong kind of node |
//! | Generated Dart analyzed | `packages/duet` CI | output that does not compile |
//! | Generated TypeScript compiled | `packages/duet-js` CI | the same, plus an unused or missing import |
//! | Generated clients driven against a host | both packages' tests | a codec that encodes what it cannot decode |
//! | `render → read → compare` | `tests/round_trip.rs` | the schema format meaning two things |
//! | Coverage floor | `tests/coverage.rs` | a `Ty` arm no fixture reaches |
//!
//! `tests/mutation.rs` measures the claim: it perturbs a path literal, a casing
//! rule and a type mapping, and records which check notices.

mod support;

use std::collections::BTreeSet;

#[test]
fn the_goldens_match_what_the_emitters_produce_now() {
    for (relative, generated) in support::all_outputs() {
        let committed = support::read(&relative);
        assert!(
            committed == generated,
            "{relative} is out of date{}\n\nRegenerate it with:\n    {}",
            support::first_difference(&committed, &generated),
            support::GENERATOR
        );
    }
}

#[test]
fn generating_twice_gives_identical_bytes() {
    // The weakest form of determinism, and the one a hash map's iteration order
    // breaks first.
    for _ in 0..4 {
        assert_eq!(support::all_outputs(), support::all_outputs());
    }
}

#[test]
fn every_generated_file_carries_the_header_and_one_trailing_newline() {
    for (relative, generated) in support::all_outputs() {
        assert!(
            generated.starts_with("// GENERATED BY duet-codegen. DO NOT EDIT BY HAND."),
            "{relative} does not say it is generated"
        );
        assert!(
            generated.contains(support::GENERATOR),
            "{relative} does not name the command that regenerates it"
        );
        assert!(generated.ends_with('\n'), "{relative} has no final newline");
        assert!(
            !generated.ends_with("\n\n"),
            "{relative} ends with more than one newline"
        );
    }
}

#[test]
fn the_goldens_cover_every_fixture_and_nothing_else() {
    // A golden nobody generates any more would keep passing `dart analyze` and
    // silently stop being checked for staleness.
    let expected: BTreeSet<String> = support::all_outputs()
        .into_iter()
        .map(|(relative, _)| relative)
        .collect();
    for directory in [
        "packages/duet/test/generated",
        "packages/duet-js/test/generated",
    ] {
        let root = support::repo_root().join(directory);
        let found: BTreeSet<String> = std::fs::read_dir(&root)
            .unwrap_or_else(|e| panic!("cannot list {}: {e}", root.display()))
            .filter_map(Result::ok)
            .map(|entry| format!("{directory}/{}", entry.file_name().to_string_lossy()))
            .collect();
        for name in &found {
            assert!(
                expected.contains(name),
                "{name} is committed but no fixture generates it"
            );
        }
    }
}

#[test]
#[ignore = "rewrites the committed goldens; run by hand, then review the diff"]
fn regenerate_goldens() {
    for (relative, generated) in support::all_outputs() {
        support::write(&relative, &generated);
    }
}
