// GENERATED BY duet-codegen. DO NOT EDIT BY HAND.
//
// Source:     examples/showcase/schema/showcase.json
// Regenerate: duet generate --schema examples/showcase/schema/showcase.json --dart examples/showcase/flutter/lib/src/showcase.duet.dart --ts examples/showcase/web/src/showcase.duet.ts
//
// Every path below is a string literal minted and validated when this
// file was generated. Nothing here builds a path out of a runtime
// value, and every path segment is the schema's own wire key, never a
// camel-cased one — the accessor names are camel-cased and the paths
// are not, deliberately, because two guests that disagree about a wire
// key silently stop seeing each other's writes.
//
// There are no algorithms here. Every decode, every merge and every
// push route lives in the hand-written Dart runtime this file
// delegates to.

/// The typed Duet client generated from `examples/showcase/schema/showcase.json`.
library;

import 'package:duet/duet.dart';
import 'package:duet/typed.dart';

/// `ComposeError`, as the schema describes it.
final class ComposeError {
  /// Creates a `ComposeError`.
  const ComposeError({required this.code, required this.detail});

  /// The `code` field.
  final String code;

  /// The `detail` field.
  final String detail;

  @override
  bool operator ==(Object other) =>
      other is ComposeError &&
      other.code == code &&
      other.detail == detail;

  @override
  int get hashCode => Object.hashAll(<Object?>[code, detail]);

  @override
  String toString() =>
      'ComposeError(code: $code, detail: $detail)';
}

/// The [DuetCodec] for [ComposeError].
final class ComposeErrorCodec implements DuetCodec<ComposeError> {
  /// Creates the codec.
  const ComposeErrorCodec();

  @override
  String get name => 'ComposeError';

  @override
  DuetValue encode(ComposeError value) {
    return DuetMap(<String, DuetValue>{
      'code': duetStringCodec.encode(value.code),
      'detail': duetStringCodec.encode(value.detail),
    });
  }

  @override
  ComposeError? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<String> code =
        duetRequiredReading<String>(duetStringCodec, value.entries['code']);
    if (code is! DuetPresent<String>) return null;
    final DuetReading<String> detail =
        duetRequiredReading<String>(duetStringCodec, value.entries['detail']);
    if (detail is! DuetPresent<String>) return null;
    return ComposeError(code: code.value, detail: detail.value);
  }
}

/// `Document`, as the schema describes it.
final class Document {
  /// Creates a `Document`.
  const Document({required this.title, required this.lines});

  /// The `title` field.
  final String title;

  /// The `lines` field.
  final List<String> lines;

  @override
  bool operator ==(Object other) =>
      other is Document &&
      other.title == title &&
      other.lines == lines;

  @override
  int get hashCode => Object.hashAll(<Object?>[title, lines]);

  @override
  String toString() =>
      'Document(title: $title, lines: $lines)';
}

/// The [DuetCodec] for [Document].
final class DocumentCodec implements DuetCodec<Document> {
  /// Creates the codec.
  const DocumentCodec();

  @override
  String get name => 'Document';

  @override
  DuetValue encode(Document value) {
    return DuetMap(<String, DuetValue>{
      'title': duetStringCodec.encode(value.title),
      'lines': duetListCodec<String>(duetStringCodec).encode(value.lines),
    });
  }

  @override
  Document? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<String> title =
        duetRequiredReading<String>(duetStringCodec, value.entries['title']);
    if (title is! DuetPresent<String>) return null;
    final DuetReading<List<String>> lines =
        duetRequiredReading<List<String>>(duetListCodec<String>(duetStringCodec), value.entries['lines']);
    if (lines is! DuetPresent<List<String>>) return null;
    return Document(title: title.value, lines: lines.value);
  }
}

/// `HostControl`, as the schema describes it.
final class HostControl {
  /// Creates a `HostControl`.
  const HostControl({required this.request});

  /// The `request` field.
  final String request;

  @override
  bool operator ==(Object other) =>
      other is HostControl &&
      other.request == request;

  @override
  int get hashCode => Object.hashAll(<Object?>[request]);

  @override
  String toString() =>
      'HostControl(request: $request)';
}

/// The [DuetCodec] for [HostControl].
final class HostControlCodec implements DuetCodec<HostControl> {
  /// Creates the codec.
  const HostControlCodec();

  @override
  String get name => 'HostControl';

  @override
  DuetValue encode(HostControl value) {
    return DuetMap(<String, DuetValue>{
      'request': duetStringCodec.encode(value.request),
    });
  }

  @override
  HostControl? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<String> request =
        duetRequiredReading<String>(duetStringCodec, value.entries['request']);
    if (request is! DuetPresent<String>) return null;
    return HostControl(request: request.value);
  }
}

/// `HostNote`, as the schema describes it.
final class HostNote {
  /// Creates a `HostNote`.
  const HostNote({required this.act, required this.detail});

  /// The `act` field.
  final String act;

  /// The `detail` field.
  final String detail;

  @override
  bool operator ==(Object other) =>
      other is HostNote &&
      other.act == act &&
      other.detail == detail;

  @override
  int get hashCode => Object.hashAll(<Object?>[act, detail]);

  @override
  String toString() =>
      'HostNote(act: $act, detail: $detail)';
}

/// The [DuetCodec] for [HostNote].
final class HostNoteCodec implements DuetCodec<HostNote> {
  /// Creates the codec.
  const HostNoteCodec();

  @override
  String get name => 'HostNote';

  @override
  DuetValue encode(HostNote value) {
    return DuetMap(<String, DuetValue>{
      'act': duetStringCodec.encode(value.act),
      'detail': duetStringCodec.encode(value.detail),
    });
  }

  @override
  HostNote? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<String> act =
        duetRequiredReading<String>(duetStringCodec, value.entries['act']);
    if (act is! DuetPresent<String>) return null;
    final DuetReading<String> detail =
        duetRequiredReading<String>(duetStringCodec, value.entries['detail']);
    if (detail is! DuetPresent<String>) return null;
    return HostNote(act: act.value, detail: detail.value);
  }
}

/// `Presence`, as the schema describes it.
final class Presence {
  /// Creates a `Presence`.
  const Presence({
    required this.status,
    required this.note,
    required this.sawPeerNote,
    required this.sawLines,
    required this.returned,
    required this.raised,
  });

  /// The `status` field.
  final String status;

  /// The `note` field.
  final String note;

  /// The `saw_peer_note` field.
  final String sawPeerNote;

  /// The `saw_lines` field.
  final int sawLines;

  /// The `returned` field.
  final String returned;

  /// The `raised` field.
  final String raised;

  @override
  bool operator ==(Object other) =>
      other is Presence &&
      other.status == status &&
      other.note == note &&
      other.sawPeerNote == sawPeerNote &&
      other.sawLines == sawLines &&
      other.returned == returned &&
      other.raised == raised;

  @override
  int get hashCode => Object.hashAll(<Object?>[
    status,
    note,
    sawPeerNote,
    sawLines,
    returned,
    raised,
  ]);

  @override
  String toString() =>
      'Presence(status: $status, note: $note, sawPeerNote: $sawPeerNote, sawLines: $sawLines, returned: $returned, raised: $raised)';
}

/// The [DuetCodec] for [Presence].
final class PresenceCodec implements DuetCodec<Presence> {
  /// Creates the codec.
  const PresenceCodec();

  @override
  String get name => 'Presence';

  @override
  DuetValue encode(Presence value) {
    return DuetMap(<String, DuetValue>{
      'status': duetStringCodec.encode(value.status),
      'note': duetStringCodec.encode(value.note),
      'saw_peer_note': duetStringCodec.encode(value.sawPeerNote),
      'saw_lines': duetIntCodec.encode(value.sawLines),
      'returned': duetStringCodec.encode(value.returned),
      'raised': duetStringCodec.encode(value.raised),
    });
  }

  @override
  Presence? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<String> status =
        duetRequiredReading<String>(duetStringCodec, value.entries['status']);
    if (status is! DuetPresent<String>) return null;
    final DuetReading<String> note =
        duetRequiredReading<String>(duetStringCodec, value.entries['note']);
    if (note is! DuetPresent<String>) return null;
    final DuetReading<String> sawPeerNote =
        duetRequiredReading<String>(duetStringCodec, value.entries['saw_peer_note']);
    if (sawPeerNote is! DuetPresent<String>) return null;
    final DuetReading<int> sawLines =
        duetRequiredReading<int>(duetIntCodec, value.entries['saw_lines']);
    if (sawLines is! DuetPresent<int>) return null;
    final DuetReading<String> returned =
        duetRequiredReading<String>(duetStringCodec, value.entries['returned']);
    if (returned is! DuetPresent<String>) return null;
    final DuetReading<String> raised =
        duetRequiredReading<String>(duetStringCodec, value.entries['raised']);
    if (raised is! DuetPresent<String>) return null;
    return Presence(
      status: status.value,
      note: note.value,
      sawPeerNote: sawPeerNote.value,
      sawLines: sawLines.value,
      returned: returned.value,
      raised: raised.value,
    );
  }
}

/// `Showcase`, as the schema describes it.
final class Showcase {
  /// Creates a `Showcase`.
  const Showcase({
    required this.document,
    required this.flutter,
    required this.web,
    required this.host,
    required this.control,
    required this.counter,
  });

  /// The `document` field.
  final Document document;

  /// The `flutter` field.
  final Presence flutter;

  /// The `web` field.
  final Presence web;

  /// The `host` field.
  final HostNote host;

  /// The `control` field.
  final HostControl control;

  /// The `counter` field.
  final int counter;

  @override
  bool operator ==(Object other) =>
      other is Showcase &&
      other.document == document &&
      other.flutter == flutter &&
      other.web == web &&
      other.host == host &&
      other.control == control &&
      other.counter == counter;

  @override
  int get hashCode => Object.hashAll(<Object?>[
    document,
    flutter,
    web,
    host,
    control,
    counter,
  ]);

  @override
  String toString() =>
      'Showcase(document: $document, flutter: $flutter, web: $web, host: $host, control: $control, counter: $counter)';
}

/// The [DuetCodec] for [Showcase].
final class ShowcaseCodec implements DuetCodec<Showcase> {
  /// Creates the codec.
  const ShowcaseCodec();

  @override
  String get name => 'Showcase';

  @override
  DuetValue encode(Showcase value) {
    return DuetMap(<String, DuetValue>{
      'document': const DocumentCodec().encode(value.document),
      'flutter': const PresenceCodec().encode(value.flutter),
      'web': const PresenceCodec().encode(value.web),
      'host': const HostNoteCodec().encode(value.host),
      'control': const HostControlCodec().encode(value.control),
      'counter': duetIntCodec.encode(value.counter),
    });
  }

  @override
  Showcase? decode(DuetValue value) {
    if (value is! DuetMap) return null;
    final DuetReading<Document> document =
        duetRequiredReading<Document>(const DocumentCodec(), value.entries['document']);
    if (document is! DuetPresent<Document>) return null;
    final DuetReading<Presence> flutter =
        duetRequiredReading<Presence>(const PresenceCodec(), value.entries['flutter']);
    if (flutter is! DuetPresent<Presence>) return null;
    final DuetReading<Presence> web =
        duetRequiredReading<Presence>(const PresenceCodec(), value.entries['web']);
    if (web is! DuetPresent<Presence>) return null;
    final DuetReading<HostNote> host =
        duetRequiredReading<HostNote>(const HostNoteCodec(), value.entries['host']);
    if (host is! DuetPresent<HostNote>) return null;
    final DuetReading<HostControl> control =
        duetRequiredReading<HostControl>(const HostControlCodec(), value.entries['control']);
    if (control is! DuetPresent<HostControl>) return null;
    final DuetReading<int> counter =
        duetRequiredReading<int>(duetIntCodec, value.entries['counter']);
    if (counter is! DuetPresent<int>) return null;
    return Showcase(
      document: document.value,
      flutter: flutter.value,
      web: web.value,
      host: host.value,
      control: control.value,
      counter: counter.value,
    );
  }
}

/// Typed accessors for `Showcase` at the store's root.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseClient {
  /// Binds these accessors to [router].
  const ShowcaseClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `Showcase` itself, as one value at the store's root.
  DuetField<Showcase> get self =>
      DuetField<Showcase>(router, '', const ShowcaseCodec());

  /// `Showcase.document`'s own accessors, at `document`.
  ShowcaseDocumentClient get document => ShowcaseDocumentClient(router);

  /// `Showcase.flutter`'s own accessors, at `flutter`.
  ShowcaseFlutterClient get flutter => ShowcaseFlutterClient(router);

  /// `Showcase.web`'s own accessors, at `web`.
  ShowcaseWebClient get web => ShowcaseWebClient(router);

  /// `Showcase.host`'s own accessors, at `host`.
  ShowcaseHostClient get host => ShowcaseHostClient(router);

  /// `Showcase.control`'s own accessors, at `control`.
  ShowcaseControlClient get control => ShowcaseControlClient(router);

  /// `Showcase.counter` at `counter`.
  DuetField<int> get counter =>
      DuetField<int>(router, 'counter', duetIntCodec);
}

/// Typed accessors for `Document` at `document`.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseDocumentClient {
  /// Binds these accessors to [router].
  const ShowcaseDocumentClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `Document` itself, as one value at `document`.
  DuetField<Document> get self =>
      DuetField<Document>(router, 'document', const DocumentCodec());

  /// `Document.title` at `document.title`.
  DuetField<String> get title =>
      DuetField<String>(router, 'document.title', duetStringCodec);

  /// `Document.lines` at `document.lines`.
  DuetField<List<String>> get lines =>
      DuetField<List<String>>(router, 'document.lines', duetListCodec<String>(duetStringCodec));
}

/// Typed accessors for `Presence` at `flutter`.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseFlutterClient {
  /// Binds these accessors to [router].
  const ShowcaseFlutterClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `Presence` itself, as one value at `flutter`.
  DuetField<Presence> get self =>
      DuetField<Presence>(router, 'flutter', const PresenceCodec());

  /// `Presence.status` at `flutter.status`.
  DuetField<String> get status =>
      DuetField<String>(router, 'flutter.status', duetStringCodec);

  /// `Presence.note` at `flutter.note`.
  DuetField<String> get note =>
      DuetField<String>(router, 'flutter.note', duetStringCodec);

  /// `Presence.saw_peer_note` at `flutter.saw_peer_note`.
  DuetField<String> get sawPeerNote =>
      DuetField<String>(router, 'flutter.saw_peer_note', duetStringCodec);

  /// `Presence.saw_lines` at `flutter.saw_lines`.
  DuetField<int> get sawLines =>
      DuetField<int>(router, 'flutter.saw_lines', duetIntCodec);

  /// `Presence.returned` at `flutter.returned`.
  DuetField<String> get returned =>
      DuetField<String>(router, 'flutter.returned', duetStringCodec);

  /// `Presence.raised` at `flutter.raised`.
  DuetField<String> get raised =>
      DuetField<String>(router, 'flutter.raised', duetStringCodec);
}

/// Typed accessors for `Presence` at `web`.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseWebClient {
  /// Binds these accessors to [router].
  const ShowcaseWebClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `Presence` itself, as one value at `web`.
  DuetField<Presence> get self =>
      DuetField<Presence>(router, 'web', const PresenceCodec());

  /// `Presence.status` at `web.status`.
  DuetField<String> get status =>
      DuetField<String>(router, 'web.status', duetStringCodec);

  /// `Presence.note` at `web.note`.
  DuetField<String> get note =>
      DuetField<String>(router, 'web.note', duetStringCodec);

  /// `Presence.saw_peer_note` at `web.saw_peer_note`.
  DuetField<String> get sawPeerNote =>
      DuetField<String>(router, 'web.saw_peer_note', duetStringCodec);

  /// `Presence.saw_lines` at `web.saw_lines`.
  DuetField<int> get sawLines =>
      DuetField<int>(router, 'web.saw_lines', duetIntCodec);

  /// `Presence.returned` at `web.returned`.
  DuetField<String> get returned =>
      DuetField<String>(router, 'web.returned', duetStringCodec);

  /// `Presence.raised` at `web.raised`.
  DuetField<String> get raised =>
      DuetField<String>(router, 'web.raised', duetStringCodec);
}

/// Typed accessors for `HostNote` at `host`.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseHostClient {
  /// Binds these accessors to [router].
  const ShowcaseHostClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `HostNote` itself, as one value at `host`.
  DuetField<HostNote> get self =>
      DuetField<HostNote>(router, 'host', const HostNoteCodec());

  /// `HostNote.act` at `host.act`.
  DuetField<String> get act =>
      DuetField<String>(router, 'host.act', duetStringCodec);

  /// `HostNote.detail` at `host.detail`.
  DuetField<String> get detail =>
      DuetField<String>(router, 'host.detail', duetStringCodec);
}

/// Typed accessors for `HostControl` at `control`.
///
/// Every path here is a literal; see this file's header.
final class ShowcaseControlClient {
  /// Binds these accessors to [router].
  const ShowcaseControlClient(this.router);

  /// The router every accessor below is bound to.
  final DuetRouter router;

  /// `HostControl` itself, as one value at `control`.
  DuetField<HostControl> get self =>
      DuetField<HostControl>(router, 'control', const HostControlCodec());

  /// `HostControl.request` at `control.request`.
  DuetField<String> get request =>
      DuetField<String>(router, 'control.request', duetStringCodec);
}

/// The commands `Showcase` declares, as typed methods.
///
/// Every command name and every argument key here is a literal; see this
/// file's header. A method returns what the command *answered*; a host that
/// refused to run it throws [DuetFailure] out of [DuetClient.invoke].
final class ShowcaseCommands {
  /// Binds these commands to [client].
  const ShowcaseCommands(this.client);

  /// The client every command below is invoked through.
  final DuetClient client;

  /// Invokes `append_line`.
  ///
  /// Returns `int`.
  /// Raises `ComposeError`.
  Future<DuetOutcome<int, ComposeError>> appendLine({required String text}) async =>
      duetDecodeOutcome<int, ComposeError>(
        await client.invoke('append_line', <String, DuetValue>{
          'text': duetStringCodec.encode(text),
        }),
        duetIntCodec,
        const ComposeErrorCodec(),
      );

  /// Invokes `increment`.
  ///
  /// Returns `int`.
  /// Raises `ComposeError`.
  Future<DuetOutcome<int, ComposeError>> increment() async =>
      duetDecodeOutcome<int, ComposeError>(
        await client.invoke('increment'),
        duetIntCodec,
        const ComposeErrorCodec(),
      );

  /// Invokes `word_count`.
  ///
  /// Returns `int`.
  /// Raises nothing; the schema declares no type, so this is the raw value.
  Future<DuetOutcome<int, DuetValue>> wordCount({required String text}) async =>
      duetDecodeOutcome<int, DuetValue>(
        await client.invoke('word_count', <String, DuetValue>{
          'text': duetStringCodec.encode(text),
        }),
        duetIntCodec,
        duetDynamicCodec,
      );
}
