//! A hand-written [`SharedState`] pair, standing in for what increment 6's
//! derive will emit.
//!
//! Hand-written **on purpose**. The schema is meant to be a specification two
//! independent producers must satisfy — a human today, the derive later — and a
//! fixture generated by the thing it is supposed to check would prove nothing.
//! Every line here is what a developer writing the impl by hand would write, so
//! it doubles as a check that the escape hatch is actually usable.

use duet_core::Value;
use duet_schema::{Bytes, DecodeError, FieldDef, NotNullable, Registry, SharedState, Ty};

/// The application's root state.
#[derive(Debug, Clone, PartialEq)]
pub struct AppState {
    pub counter: i64,
    pub title: Option<String>,
    pub editor: Option<Editor>,
    pub tags: Vec<String>,
    pub thumbnail: Bytes,
}

/// A nested struct, reached through an `Option`.
#[derive(Debug, Clone, PartialEq)]
pub struct Editor {
    pub zoom: f64,
    pub theme: String,
}

impl AppState {
    /// The fixture every test starts from.
    pub fn sample() -> AppState {
        AppState {
            counter: 0,
            title: None,
            editor: Some(Editor {
                zoom: 1.0,
                theme: "dark".to_string(),
            }),
            tags: vec!["draft".to_string()],
            thumbnail: Bytes(vec![0xDE, 0xAD]),
        }
    }
}

/// Reads one required key out of a map, or reports it missing.
///
/// Every field of a schema type is materialized by `install`, so a missing key
/// means the store does not hold this type at all — a mismatch, not a default
/// to fill in silently.
fn field<'a>(
    entries: &'a std::collections::BTreeMap<String, Value>,
    type_name: &'static str,
    key: &'static str,
) -> Result<&'a Value, DecodeError> {
    entries
        .get(key)
        .ok_or_else(|| DecodeError::missing_field(type_name, key))
}

impl SharedState for AppState {
    fn to_value(&self) -> Value {
        Value::map([
            ("counter", self.counter.to_value()),
            ("title", self.title.to_value()),
            ("editor", self.editor.to_value()),
            ("tags", self.tags.to_value()),
            ("thumbnail", self.thumbnail.to_value()),
        ])
    }

    fn from_value(value: &Value) -> Result<Self, DecodeError> {
        let Value::Map(entries) = value else {
            return Err(DecodeError::wrong_type("AppState", value));
        };
        Ok(AppState {
            counter: i64::from_value(field(entries, "AppState", "counter")?)
                .map_err(|e| e.within_key("counter"))?,
            title: Option::from_value(field(entries, "AppState", "title")?)
                .map_err(|e| e.within_key("title"))?,
            editor: Option::from_value(field(entries, "AppState", "editor")?)
                .map_err(|e| e.within_key("editor"))?,
            tags: Vec::from_value(field(entries, "AppState", "tags")?)
                .map_err(|e| e.within_key("tags"))?,
            thumbnail: Bytes::from_value(field(entries, "AppState", "thumbnail")?)
                .map_err(|e| e.within_key("thumbnail"))?,
        })
    }

    fn schema(registry: &mut Registry) -> Ty {
        registry.define::<Self>("AppState", |r| {
            vec![
                FieldDef::new("counter", i64::schema(r)),
                FieldDef::new("title", Option::<String>::schema(r)),
                FieldDef::new("editor", Option::<Editor>::schema(r)),
                FieldDef::new("tags", Vec::<String>::schema(r)),
                FieldDef::new("thumbnail", Bytes::schema(r)),
            ]
        })
    }
}

impl NotNullable for AppState {}

impl SharedState for Editor {
    fn to_value(&self) -> Value {
        Value::map([
            ("zoom", self.zoom.to_value()),
            ("theme", self.theme.to_value()),
        ])
    }

    fn from_value(value: &Value) -> Result<Self, DecodeError> {
        let Value::Map(entries) = value else {
            return Err(DecodeError::wrong_type("Editor", value));
        };
        Ok(Editor {
            zoom: f64::from_value(field(entries, "Editor", "zoom")?)
                .map_err(|e| e.within_key("zoom"))?,
            theme: String::from_value(field(entries, "Editor", "theme")?)
                .map_err(|e| e.within_key("theme"))?,
        })
    }

    fn schema(registry: &mut Registry) -> Ty {
        registry.define::<Self>("Editor", |r| {
            vec![
                FieldDef::new("zoom", f64::schema(r)),
                FieldDef::new("theme", String::schema(r)),
            ]
        })
    }
}

impl NotNullable for Editor {}
