// GENERATED BY duet-codegen. DO NOT EDIT BY HAND.
//
// Source:     examples/showcase/schema/showcase.json
// Regenerate: duet generate --schema examples/showcase/schema/showcase.json --dart examples/showcase/flutter/lib/src/showcase.duet.dart --ts examples/showcase/web/src/showcase.duet.ts
//
// Every path below is a string literal minted and validated when this
// file was generated. Nothing here builds a path out of a runtime
// value, and every path segment is the schema's own wire key, never a
// camel-cased one — the accessor names are camel-cased and the paths
// are not, deliberately, because two guests that disagree about a wire
// key silently stop seeing each other's writes.
//
// There are no algorithms here. Every decode, every merge and every
// push route lives in the hand-written TypeScript runtime this file
// delegates to.

/**
 * The typed Duet client generated from `examples/showcase/schema/showcase.json`.
 *
 * @module
 */

import {
  duetMap,
  type DuetClient,
  type DuetValue,
} from 'duet-protocol';

import {
  DuetField,
  duetDecodeOutcome,
  duetDynamicCodec,
  duetIntCodec,
  duetListCodec,
  duetRequiredReading,
  duetStringCodec,
  type DuetCodec,
  type DuetOutcome,
  type DuetRouter,
} from 'duet-protocol/typed';

/** `ComposeError`, as the schema describes it. */
export interface ComposeError {
  /** The `code` field. */
  readonly code: string;
  /** The `detail` field. */
  readonly detail: string;
}

/** The codec for {@link ComposeError}. */
export const composeErrorCodec: DuetCodec<ComposeError> = {
  name: 'ComposeError',
  encode: (value) =>
    duetMap(
      new Map<string, DuetValue>([
        ['code', duetStringCodec.encode(value.code)],
        ['detail', duetStringCodec.encode(value.detail)],
      ]),
    ),
  decode: (value) => {
    if (value.kind !== 'map') return null;
    const code = duetRequiredReading(
      duetStringCodec,
      value.entries.get('code') ?? null,
    );
    if (code.kind !== 'present') return null;
    const detail = duetRequiredReading(
      duetStringCodec,
      value.entries.get('detail') ?? null,
    );
    if (detail.kind !== 'present') return null;
    return { code: code.value, detail: detail.value };
  },
};

/** `Document`, as the schema describes it. */
export interface Document {
  /** The `title` field. */
  readonly title: string;
  /** The `lines` field. */
  readonly lines: string[];
}

/** The codec for {@link Document}. */
export const documentCodec: DuetCodec<Document> = {
  name: 'Document',
  encode: (value) =>
    duetMap(
      new Map<string, DuetValue>([
        ['title', duetStringCodec.encode(value.title)],
        ['lines', duetListCodec<string>(duetStringCodec).encode(value.lines)],
      ]),
    ),
  decode: (value) => {
    if (value.kind !== 'map') return null;
    const title = duetRequiredReading(
      duetStringCodec,
      value.entries.get('title') ?? null,
    );
    if (title.kind !== 'present') return null;
    const lines = duetRequiredReading(
      duetListCodec<string>(duetStringCodec),
      value.entries.get('lines') ?? null,
    );
    if (lines.kind !== 'present') return null;
    return { title: title.value, lines: lines.value };
  },
};

/** `HostNote`, as the schema describes it. */
export interface HostNote {
  /** The `act` field. */
  readonly act: string;
  /** The `detail` field. */
  readonly detail: string;
}

/** The codec for {@link HostNote}. */
export const hostNoteCodec: DuetCodec<HostNote> = {
  name: 'HostNote',
  encode: (value) =>
    duetMap(
      new Map<string, DuetValue>([
        ['act', duetStringCodec.encode(value.act)],
        ['detail', duetStringCodec.encode(value.detail)],
      ]),
    ),
  decode: (value) => {
    if (value.kind !== 'map') return null;
    const act = duetRequiredReading(
      duetStringCodec,
      value.entries.get('act') ?? null,
    );
    if (act.kind !== 'present') return null;
    const detail = duetRequiredReading(
      duetStringCodec,
      value.entries.get('detail') ?? null,
    );
    if (detail.kind !== 'present') return null;
    return { act: act.value, detail: detail.value };
  },
};

/** `Presence`, as the schema describes it. */
export interface Presence {
  /** The `status` field. */
  readonly status: string;
  /** The `note` field. */
  readonly note: string;
  /** The `saw_peer_note` field. */
  readonly sawPeerNote: string;
  /** The `saw_lines` field. */
  readonly sawLines: bigint;
  /** The `returned` field. */
  readonly returned: string;
  /** The `raised` field. */
  readonly raised: string;
}

/** The codec for {@link Presence}. */
export const presenceCodec: DuetCodec<Presence> = {
  name: 'Presence',
  encode: (value) =>
    duetMap(
      new Map<string, DuetValue>([
        ['status', duetStringCodec.encode(value.status)],
        ['note', duetStringCodec.encode(value.note)],
        ['saw_peer_note', duetStringCodec.encode(value.sawPeerNote)],
        ['saw_lines', duetIntCodec.encode(value.sawLines)],
        ['returned', duetStringCodec.encode(value.returned)],
        ['raised', duetStringCodec.encode(value.raised)],
      ]),
    ),
  decode: (value) => {
    if (value.kind !== 'map') return null;
    const status = duetRequiredReading(
      duetStringCodec,
      value.entries.get('status') ?? null,
    );
    if (status.kind !== 'present') return null;
    const note = duetRequiredReading(
      duetStringCodec,
      value.entries.get('note') ?? null,
    );
    if (note.kind !== 'present') return null;
    const sawPeerNote = duetRequiredReading(
      duetStringCodec,
      value.entries.get('saw_peer_note') ?? null,
    );
    if (sawPeerNote.kind !== 'present') return null;
    const sawLines = duetRequiredReading(
      duetIntCodec,
      value.entries.get('saw_lines') ?? null,
    );
    if (sawLines.kind !== 'present') return null;
    const returned = duetRequiredReading(
      duetStringCodec,
      value.entries.get('returned') ?? null,
    );
    if (returned.kind !== 'present') return null;
    const raised = duetRequiredReading(
      duetStringCodec,
      value.entries.get('raised') ?? null,
    );
    if (raised.kind !== 'present') return null;
    return {
      status: status.value,
      note: note.value,
      sawPeerNote: sawPeerNote.value,
      sawLines: sawLines.value,
      returned: returned.value,
      raised: raised.value,
    };
  },
};

/** `Showcase`, as the schema describes it. */
export interface Showcase {
  /** The `document` field. */
  readonly document: Document;
  /** The `flutter` field. */
  readonly flutter: Presence;
  /** The `web` field. */
  readonly web: Presence;
  /** The `host` field. */
  readonly host: HostNote;
}

/** The codec for {@link Showcase}. */
export const showcaseCodec: DuetCodec<Showcase> = {
  name: 'Showcase',
  encode: (value) =>
    duetMap(
      new Map<string, DuetValue>([
        ['document', documentCodec.encode(value.document)],
        ['flutter', presenceCodec.encode(value.flutter)],
        ['web', presenceCodec.encode(value.web)],
        ['host', hostNoteCodec.encode(value.host)],
      ]),
    ),
  decode: (value) => {
    if (value.kind !== 'map') return null;
    const document = duetRequiredReading(
      documentCodec,
      value.entries.get('document') ?? null,
    );
    if (document.kind !== 'present') return null;
    const flutter = duetRequiredReading(
      presenceCodec,
      value.entries.get('flutter') ?? null,
    );
    if (flutter.kind !== 'present') return null;
    const web = duetRequiredReading(
      presenceCodec,
      value.entries.get('web') ?? null,
    );
    if (web.kind !== 'present') return null;
    const host = duetRequiredReading(
      hostNoteCodec,
      value.entries.get('host') ?? null,
    );
    if (host.kind !== 'present') return null;
    return {
      document: document.value,
      flutter: flutter.value,
      web: web.value,
      host: host.value,
    };
  },
};

/**
 * Typed accessors for `Showcase` at the store's root.
 *
 * Every path here is a literal; see this file's header.
 */
export class ShowcaseClient {
  /** The router every accessor below is bound to. */
  readonly router: DuetRouter;

  /** Binds these accessors to `router`. */
  constructor(router: DuetRouter) {
    this.router = router;
  }

  /** `Showcase` itself, as one value at the store's root. */
  get self(): DuetField<Showcase> {
    return new DuetField<Showcase>(this.router, '', showcaseCodec);
  }

  /** `Showcase.document`'s own accessors, at `document`. */
  get document(): ShowcaseDocumentClient {
    return new ShowcaseDocumentClient(this.router);
  }

  /** `Showcase.flutter`'s own accessors, at `flutter`. */
  get flutter(): ShowcaseFlutterClient {
    return new ShowcaseFlutterClient(this.router);
  }

  /** `Showcase.web`'s own accessors, at `web`. */
  get web(): ShowcaseWebClient {
    return new ShowcaseWebClient(this.router);
  }

  /** `Showcase.host`'s own accessors, at `host`. */
  get host(): ShowcaseHostClient {
    return new ShowcaseHostClient(this.router);
  }
}

/**
 * Typed accessors for `Document` at `document`.
 *
 * Every path here is a literal; see this file's header.
 */
export class ShowcaseDocumentClient {
  /** The router every accessor below is bound to. */
  readonly router: DuetRouter;

  /** Binds these accessors to `router`. */
  constructor(router: DuetRouter) {
    this.router = router;
  }

  /** `Document` itself, as one value at `document`. */
  get self(): DuetField<Document> {
    return new DuetField<Document>(this.router, 'document', documentCodec);
  }

  /** `Document.title` at `document.title`. */
  get title(): DuetField<string> {
    return new DuetField<string>(this.router, 'document.title', duetStringCodec);
  }

  /** `Document.lines` at `document.lines`. */
  get lines(): DuetField<string[]> {
    return new DuetField<string[]>(this.router, 'document.lines', duetListCodec<string>(duetStringCodec));
  }
}

/**
 * Typed accessors for `Presence` at `flutter`.
 *
 * Every path here is a literal; see this file's header.
 */
export class ShowcaseFlutterClient {
  /** The router every accessor below is bound to. */
  readonly router: DuetRouter;

  /** Binds these accessors to `router`. */
  constructor(router: DuetRouter) {
    this.router = router;
  }

  /** `Presence` itself, as one value at `flutter`. */
  get self(): DuetField<Presence> {
    return new DuetField<Presence>(this.router, 'flutter', presenceCodec);
  }

  /** `Presence.status` at `flutter.status`. */
  get status(): DuetField<string> {
    return new DuetField<string>(this.router, 'flutter.status', duetStringCodec);
  }

  /** `Presence.note` at `flutter.note`. */
  get note(): DuetField<string> {
    return new DuetField<string>(this.router, 'flutter.note', duetStringCodec);
  }

  /** `Presence.saw_peer_note` at `flutter.saw_peer_note`. */
  get sawPeerNote(): DuetField<string> {
    return new DuetField<string>(this.router, 'flutter.saw_peer_note', duetStringCodec);
  }

  /** `Presence.saw_lines` at `flutter.saw_lines`. */
  get sawLines(): DuetField<bigint> {
    return new DuetField<bigint>(this.router, 'flutter.saw_lines', duetIntCodec);
  }

  /** `Presence.returned` at `flutter.returned`. */
  get returned(): DuetField<string> {
    return new DuetField<string>(this.router, 'flutter.returned', duetStringCodec);
  }

  /** `Presence.raised` at `flutter.raised`. */
  get raised(): DuetField<string> {
    return new DuetField<string>(this.router, 'flutter.raised', duetStringCodec);
  }
}

/**
 * Typed accessors for `Presence` at `web`.
 *
 * Every path here is a literal; see this file's header.
 */
export class ShowcaseWebClient {
  /** The router every accessor below is bound to. */
  readonly router: DuetRouter;

  /** Binds these accessors to `router`. */
  constructor(router: DuetRouter) {
    this.router = router;
  }

  /** `Presence` itself, as one value at `web`. */
  get self(): DuetField<Presence> {
    return new DuetField<Presence>(this.router, 'web', presenceCodec);
  }

  /** `Presence.status` at `web.status`. */
  get status(): DuetField<string> {
    return new DuetField<string>(this.router, 'web.status', duetStringCodec);
  }

  /** `Presence.note` at `web.note`. */
  get note(): DuetField<string> {
    return new DuetField<string>(this.router, 'web.note', duetStringCodec);
  }

  /** `Presence.saw_peer_note` at `web.saw_peer_note`. */
  get sawPeerNote(): DuetField<string> {
    return new DuetField<string>(this.router, 'web.saw_peer_note', duetStringCodec);
  }

  /** `Presence.saw_lines` at `web.saw_lines`. */
  get sawLines(): DuetField<bigint> {
    return new DuetField<bigint>(this.router, 'web.saw_lines', duetIntCodec);
  }

  /** `Presence.returned` at `web.returned`. */
  get returned(): DuetField<string> {
    return new DuetField<string>(this.router, 'web.returned', duetStringCodec);
  }

  /** `Presence.raised` at `web.raised`. */
  get raised(): DuetField<string> {
    return new DuetField<string>(this.router, 'web.raised', duetStringCodec);
  }
}

/**
 * Typed accessors for `HostNote` at `host`.
 *
 * Every path here is a literal; see this file's header.
 */
export class ShowcaseHostClient {
  /** The router every accessor below is bound to. */
  readonly router: DuetRouter;

  /** Binds these accessors to `router`. */
  constructor(router: DuetRouter) {
    this.router = router;
  }

  /** `HostNote` itself, as one value at `host`. */
  get self(): DuetField<HostNote> {
    return new DuetField<HostNote>(this.router, 'host', hostNoteCodec);
  }

  /** `HostNote.act` at `host.act`. */
  get act(): DuetField<string> {
    return new DuetField<string>(this.router, 'host.act', duetStringCodec);
  }

  /** `HostNote.detail` at `host.detail`. */
  get detail(): DuetField<string> {
    return new DuetField<string>(this.router, 'host.detail', duetStringCodec);
  }
}

/**
 * The commands `Showcase` declares, as typed methods.
 *
 * Every command name and every argument key here is a literal; see this
 * file's header. A method resolves with what the command *answered*; a host
 * that refused to run it rejects with a `DuetFailure` from
 * `DuetClient.invoke`.
 */
export class ShowcaseCommands {
  /** The client every command below is invoked through. */
  readonly client: DuetClient;

  /** Binds these commands to `client`. */
  constructor(client: DuetClient) {
    this.client = client;
  }

  /**
   * Invokes `append_line`.
   *
   * Returns `bigint`.
   * Raises `ComposeError`.
   */
  async appendLine(params: {
    readonly text: string;
  }): Promise<DuetOutcome<bigint, ComposeError>> {
    return duetDecodeOutcome<bigint, ComposeError>(
      await this.client.invoke('append_line', new Map<string, DuetValue>([
        ['text', duetStringCodec.encode(params.text)],
      ])),
      duetIntCodec,
      composeErrorCodec,
    );
  }

  /**
   * Invokes `word_count`.
   *
   * Returns `bigint`.
   * Raises nothing; the schema declares no type, so this is the raw value.
   */
  async wordCount(params: {
    readonly text: string;
  }): Promise<DuetOutcome<bigint, DuetValue>> {
    return duetDecodeOutcome<bigint, DuetValue>(
      await this.client.invoke('word_count', new Map<string, DuetValue>([
        ['text', duetStringCodec.encode(params.text)],
      ])),
      duetIntCodec,
      duetDynamicCodec,
    );
  }
}
