/**
 * Reading `corpus/schema-corpus.json`.
 *
 * Mirrors `packages/duet/test/support/schema_corpus.dart`.
 *
 * The corpus is generated by the Rust workspace
 * (`cargo test -p duet-codegen --test schema_corpus -- --ignored
 * regenerate_corpus`) and consumed as a peer by every guest. It lives outside
 * every language's tree because none of them owns it.
 *
 * Two files here read it, for two different reasons:
 *
 * - `schema-corpus.test.ts` checks the **generated codecs** against it with no
 *   host at all: the wire keys each struct occupies, the values each field
 *   admits, the values each field must refuse, and the seed walked by path.
 * - `live-host.test.ts` uses it as the *input* to a run against the real host:
 *   which paths exist, what to write at each, and what a store holds before
 *   anything is written.
 *
 * One reader, so the two cannot disagree about what the file says.
 *
 * @module
 */

import { existsSync, readFileSync } from 'node:fs';

import { decodeValueText, type DuetValue } from '../../src/index.ts';

/**
 * Where the corpus lives, relative to this package's root — which is the
 * working directory `npm test` runs in.
 */
export const CORPUS_PATH = '../../corpus/schema-corpus.json';

/** The schema version this file knows how to read. */
export const SCHEMA_CORPUS_VERSION = 1;

/** The command that regenerates the corpus, named in every diagnostic. */
export const CORPUS_GENERATOR =
  'cargo test -p duet-codegen --test schema_corpus -- --ignored regenerate_corpus';

/** One field of one schema type. */
export interface CorpusField {
  /** The wire key this field occupies in its struct's map. */
  readonly key: string;
  /** How the corpus spells this field's type. */
  readonly ty: string;
  /** True when the field is an `Option<T>`. */
  readonly optional: boolean;
  /** A value the field's type admits. */
  readonly accept: DuetValue;
  /** Values the field's type must refuse. Empty only for `dynamic`. */
  readonly rejects: DuetValue[];
}

/** One path a generated client binds. */
export interface CorpusPath {
  /** The whole wire path from the store's root; `''` at the root. */
  readonly path: string;
  /** How the corpus spells the type at this path. */
  readonly ty: string;
  /** True when the path holds an `Option<T>`. */
  readonly optional: boolean;
  /**
   * What a seeded store holds here, or `null` when nothing is here at all.
   *
   * `null` is **not** a `DuetNull`: it means the path addresses no node, which
   * is the state every path below a `None` struct is in. The wire spells the
   * other one `{"t":"n"}`.
   */
  readonly seed: DuetValue | null;
  /** A value the type at this path admits. */
  readonly accept: DuetValue;
  /** Values the type at this path must refuse. */
  readonly rejects: DuetValue[];
}

/** One schema's whole entry. */
export interface CorpusSchema {
  /** The fixture name: what `duet-host-stdio` is started with. */
  readonly name: string;
  /** The schema file this was generated from. */
  readonly source: string;
  /** The root type's name. */
  readonly root: string;
  /** What a store holds before anything is written. */
  readonly seed: DuetValue;
  /** Every struct, by name, with its fields in declaration order. */
  readonly types: Map<string, CorpusField[]>;
  /** Every path a generated client binds, ordered by path. */
  readonly paths: CorpusPath[];
}

/** The whole corpus. */
export interface SchemaCorpus {
  /** The corpus format version. */
  readonly version: number;
  /** The command that regenerates it. */
  readonly generator: string;
  /** Every schema, by fixture name. */
  readonly schemas: Map<string, CorpusSchema>;
}

/** Reads and parses the committed corpus. */
export function loadSchemaCorpus(): SchemaCorpus {
  if (!existsSync(CORPUS_PATH)) {
    throw new Error(
      `cannot find the schema corpus at ${CORPUS_PATH} (working directory ` +
        `${process.cwd()}). It is generated by the Rust workspace with:\n    ` +
        CORPUS_GENERATOR,
    );
  }
  const document = object(JSON.parse(readFileSync(CORPUS_PATH, 'utf8')), 'the corpus');
  const version = document['version'];
  if (typeof version !== 'number') throw new Error('the corpus has no numeric version');
  return {
    version,
    generator: text(document, 'generator'),
    schemas: new Map(
      objects(document, 'schemas').map((entry) => {
        const schema = readSchema(entry);
        return [schema.name, schema];
      }),
    ),
  };
}

/** The entry for the path `path` of `schema`. */
export function pathAt(schema: CorpusSchema, path: string): CorpusPath {
  const found = schema.paths.find((p) => p.path === path);
  if (found === undefined) {
    throw new Error(`the corpus has no path "${path}" in schema "${schema.name}"`);
  }
  return found;
}

/** The entry for the fixture named `name`. */
export function schemaNamed(corpus: SchemaCorpus, name: string): CorpusSchema {
  const found = corpus.schemas.get(name);
  if (found === undefined) throw new Error(`the corpus has no schema "${name}"`);
  return found;
}

function readSchema(entry: Record<string, unknown>): CorpusSchema {
  return {
    name: text(entry, 'name'),
    source: text(entry, 'source'),
    root: text(entry, 'root'),
    seed: decodeValueText(text(entry, 'seed')),
    types: new Map(
      objects(entry, 'types').map((type) => [
        text(type, 'name'),
        objects(type, 'fields').map(readField),
      ]),
    ),
    paths: objects(entry, 'paths').map(readPath),
  };
}

function readField(entry: Record<string, unknown>): CorpusField {
  return {
    key: text(entry, 'key'),
    ty: text(entry, 'ty'),
    optional: flag(entry, 'optional'),
    accept: decodeValueText(text(entry, 'accept')),
    rejects: wires(entry, 'rejects'),
  };
}

function readPath(entry: Record<string, unknown>): CorpusPath {
  const seed = entry['seed'];
  return {
    path: text(entry, 'path'),
    ty: text(entry, 'ty'),
    optional: flag(entry, 'optional'),
    seed: seed === null ? null : decodeValueText(asString(seed, 'seed')),
    accept: decodeValueText(text(entry, 'accept')),
    rejects: wires(entry, 'rejects'),
  };
}

function object(value: unknown, what: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`${what} is not a JSON object`);
  }
  return value as Record<string, unknown>;
}

function asString(value: unknown, field: string): string {
  if (typeof value !== 'string') throw new Error(`"${field}" is not a string`);
  return value;
}

function text(entry: Record<string, unknown>, field: string): string {
  return asString(entry[field], field);
}

function flag(entry: Record<string, unknown>, field: string): boolean {
  const value = entry[field];
  if (typeof value !== 'boolean') throw new Error(`"${field}" is not a boolean`);
  return value;
}

function objects(entry: Record<string, unknown>, field: string): Record<string, unknown>[] {
  const value = entry[field];
  if (!Array.isArray(value)) throw new Error(`"${field}" is not an array`);
  return value.map((item) => object(item, `an entry of "${field}"`));
}

function wires(entry: Record<string, unknown>, field: string): DuetValue[] {
  const value = entry[field];
  if (!Array.isArray(value)) throw new Error(`"${field}" is not an array`);
  return value.map((item) => decodeValueText(asString(item, field)));
}
