/**
 * The Duet wire protocol in TypeScript.
 *
 * Duet is a Rust host that owns shared state, with guests — a Flutter engine, a
 * `wry` webview — reading and writing it over a tagged-JSON protocol. This
 * package is the JavaScript half of that protocol, and it depends on nothing at
 * all: zero runtime dependencies, no DOM, no Node built-ins.
 *
 * Three layers, each usable on its own:
 *
 * - {@link DuetValue} and the value codec: the mirror of `duet_core::Value` and
 *   `duet-codec`.
 * - {@link DuetRequest}, {@link DuetResponse} and {@link DuetPush}: the message
 *   envelope, the mirror of `duet-protocol`.
 * - {@link DuetClient}: the guest API — `get`, `set`, `subscribe`,
 *   `unsubscribe` and pushes — over a {@link DuetTransport} the caller supplies.
 *
 * The `wry` adapter lives in its own module so that nothing in the core pulls
 * in a webview assumption; import it from `duet-protocol/wry`.
 *
 * # Conformance
 *
 * `test/wire-corpus.test.ts` runs this package against
 * `corpus/wire-corpus.json`, the golden wire corpus generated by the Rust
 * workspace and consumed as a peer by every implementation. Every accept case
 * is decoded, compared against a witness written in a deliberately *different*
 * representation, and re-encoded; every reject case must be refused, for the
 * recorded reason.
 *
 * @module
 */

export {
  DuetCodecError,
  DuetError,
  DuetFailure,
  DuetReason,
  DuetTransportError,
  DUET_REASONS,
  echoBounded,
  MAX_ECHO_CHARS,
  MAX_JSON_DEPTH,
} from './errors.ts';

export {
  compareDuetMapKeys,
  decodeDuetJson,
  encodeDuetJson,
  hasUnpairedSurrogate,
  isCanonicalSignedDecimal,
  isCanonicalUnsignedDigits,
  jsonTypeName,
  type CanonicalJson,
} from './json.ts';

export { decodeBase64, encodeBase64 } from './base64.ts';

export {
  decodeOptionalValue,
  decodeValue,
  decodeValueText,
  duetBool,
  duetBytes,
  duetFloat,
  duetInt,
  duetList,
  duetMap,
  duetNull,
  duetStr,
  duetValueEquals,
  encodeOptionalValue,
  encodeValue,
  encodeValueText,
  MAX_DUET_INT,
  MIN_DUET_INT,
  type DuetBool,
  type DuetBytes,
  type DuetFloat,
  type DuetInt,
  type DuetList,
  type DuetMap,
  type DuetNull,
  type DuetStr,
  type DuetValue,
} from './value.ts';

export {
  duetPathEquals,
  duetPathIsPrefixOf,
  duetSegmentEquals,
  DUET_ROOT_PATH,
  formatDuetPath,
  MAX_DUET_INDEX,
  parseDuetPath,
  type DuetIndexSegment,
  type DuetKeySegment,
  type DuetPath,
  type DuetSegment,
} from './path.ts';

export {
  decodeNotification,
  decodePush,
  decodePushText,
  decodeRequest,
  decodeRequestText,
  decodeResponse,
  decodeResponseText,
  DUET_CHANNEL_NAME,
  encodeNotification,
  encodePush,
  encodePushText,
  encodeRequest,
  encodeRequestText,
  encodeResponse,
  encodeResponseText,
  MAX_WIRE_ID,
  tryParseWireId,
  type DuetDoneResponse,
  type DuetFailedResponse,
  type DuetGetRequest,
  type DuetInvokeRequest,
  type DuetNotification,
  type DuetNotificationPush,
  type DuetPush,
  type DuetRaisedResponse,
  type DuetRequest,
  type DuetResponse,
  type DuetReturnedResponse,
  type DuetSetRequest,
  type DuetSubscribeRequest,
  type DuetSubscribedResponse,
  type DuetUnsubscribeRequest,
  type DuetValueResponse,
} from './message.ts';

export type { DuetTransport } from './transport.ts';
export {
  DuetClient,
  type DuetInvocation,
  type DuetRaised,
  type DuetReturned,
  type DuetSubscription,
} from './client.ts';
