//! What both emitters share: the options they take, the header they write, and
//! the pair of files they produce.

use duet_schema::Schema;

use crate::dart;
use crate::error::EmitError;
use crate::plan::Plan;
use crate::ts;

/// Where a generated TypeScript file imports the hand-written runtime from.
///
/// A parameter rather than a constant because the committed goldens live
/// *inside* `packages/duet-js`, where the package cannot import itself by name
/// without a build having run first. Every other test file in that package
/// reaches into `src` the same way, and making this an input keeps
/// "identical input ⇒ byte-identical output" true rather than adding a hidden
/// mode to the emitter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsImports {
    /// The module holding `DuetValue` and the value constructors.
    pub root: String,
    /// The module holding the typed runtime.
    pub typed: String,
}

impl Default for TsImports {
    /// What a third party gets: the published package's own entry points.
    fn default() -> TsImports {
        TsImports {
            root: "duet-protocol".to_string(),
            typed: "duet-protocol/typed".to_string(),
        }
    }
}

/// Everything the emitters need beyond the schema itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    /// Where the schema came from, named in the header so a reader of the
    /// generated file can find the source of truth.
    pub source: String,
    /// The **exact** command that regenerates the output.
    ///
    /// Named in the header and in the staleness failure, because a generated
    /// file whose header says "regenerate it" without saying how is a file
    /// people edit by hand.
    pub command: String,
    /// Where the TypeScript output imports the runtime from.
    pub ts_imports: TsImports,
}

impl Options {
    /// Options naming `source`, regenerated by `command`, importing the
    /// published package.
    pub fn new(source: impl Into<String>, command: impl Into<String>) -> Options {
        Options {
            source: source.into(),
            command: command.into(),
            ts_imports: TsImports::default(),
        }
    }
}

/// One schema's worth of generated source, in both languages.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    /// The Dart client.
    pub dart: String,
    /// The TypeScript client.
    pub ts: String,
}

/// Emits a typed Dart client and a typed TypeScript client for `schema`.
///
/// Deterministic: the same schema and the same options produce byte-identical
/// output, including ordering and the single trailing newline. Nothing here
/// reads a clock, an environment variable or a hash map's iteration order.
///
/// # Errors
///
/// [`EmitError`] when the schema is valid but has no faithful spelling in the
/// two target languages. See [`Plan::build`].
pub fn generate(schema: &Schema, options: &Options) -> Result<Generated, EmitError> {
    let plan = Plan::build(schema)?;
    Ok(Generated {
        dart: dart::emit(&plan, options),
        ts: ts::emit(&plan, options),
    })
}

/// The lines every generated file opens with, each already prefixed by `//`.
///
/// The same words in both languages: a reader who has learned what a generated
/// Duet file promises has learned it once.
pub(crate) fn header(options: &Options, language: &str) -> String {
    let Options {
        source, command, ..
    } = options;
    format!(
        "// GENERATED BY duet-codegen. DO NOT EDIT BY HAND.\n\
         //\n\
         // Source:     {source}\n\
         // Regenerate: {command}\n\
         //\n\
         // Every path below is a string literal minted and validated when this\n\
         // file was generated. Nothing here builds a path out of a runtime\n\
         // value, and every path segment is the schema's own wire key, never a\n\
         // camel-cased one — the accessor names are camel-cased and the paths\n\
         // are not, deliberately, because two guests that disagree about a wire\n\
         // key silently stop seeing each other's writes.\n\
         //\n\
         // There are no algorithms here. Every decode, every merge and every\n\
         // push route lives in the hand-written {language} runtime this file\n\
         // delegates to.\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_default_imports_are_the_published_package() {
        // The goldens are generated with in-repo specifiers; a third party gets
        // these. Pinned so the in-repo override cannot quietly become the only
        // spelling the emitter knows.
        let imports = TsImports::default();
        assert_eq!(imports.root, "duet-protocol");
        assert_eq!(imports.typed, "duet-protocol/typed");
    }

    #[test]
    fn the_header_names_the_source_and_the_exact_command() {
        let options = Options::new("schema/app.json", "cargo run --example regenerate");
        let header = header(&options, "Dart");
        assert!(header.contains("schema/app.json"));
        assert!(header.contains("cargo run --example regenerate"));
        assert!(header.contains("DO NOT EDIT BY HAND"));
        assert!(header.contains("Dart"));
        assert!(header.lines().all(|line| line.starts_with("//")));
        assert!(header.ends_with('\n'));
    }
}
