/// Conformance against the cross-language golden wire corpus.
///
/// `corpus/wire-corpus.json` is generated by the Rust workspace
/// (`cargo test -p duet-protocol --test wire_corpus -- --ignored
/// regenerate_corpus`) and consumed as a peer by every implementation of the
/// format. It lives outside every language's tree because none of them owns it.
///
/// Four cross-language divergences have already been found and fixed in this
/// project, none of which a single-language round-trip test could see:
/// non-canonical ids causing a silent hang, `-0.0` losing its sign in
/// JavaScript, an id domain wider in Rust than Dart can represent, and map key
/// order differing between UTF-8 bytes and UTF-16 code units. This file is what
/// stops the next one.
///
/// # Why the witness is not just the wire JSON again
///
/// If the expectation were JSON of the same shape as the wire, this file could
/// satisfy every accept case by parsing the wire text and echoing it back —
/// never exercising a decoder at all. Every witness below is therefore built
/// **from the decoded value**, in a deliberately different representation:
/// floats as IEEE-754 bits in hex, strings as UTF-8 byte arrays, maps as
/// ordered entry arrays. See crates/duet-protocol/tests/corpus/witness.rs.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:duet/duet.dart';
import 'package:test/test.dart';

/// Where the corpus lives, relative to this package's root — which is the
/// working directory `dart test` runs in.
const String _corpusPath = '../../corpus/wire-corpus.json';

/// The schema version this file knows how to read.
const int _schemaVersion = 1;

/// How deep `equals` may recurse when comparing a witness.
///
/// `package:matcher`'s default is 100, and `value/nesting/at_limit` is deeper
/// than that on purpose: it is a value at the wire's exact ceiling of
/// [maxJsonDepth] containers, and its witness nests once per container. Without
/// this the matcher reports "recursion depth limit exceeded" — a failure of the
/// *assertion*, not of the decoder, and one that looks alarmingly like a real
/// divergence. Comfortably above the ceiling, so it can never be what fails.
const int _matcherRecursionLimit = 4 * maxJsonDepth;

/// The case counts the corpus must contain.
///
/// Pinned as literals on purpose. A corpus test that silently consumes
/// whatever it is given is worthless: a file truncated to one case would pass
/// every assertion below and prove nothing. If these numbers need changing,
/// that is a deliberate review step.
const int _acceptCaseCount = 51;
const int _rejectCaseCount = 26;

void main() {
  final Map<String, Object?> corpus = _loadCorpus();
  final List<Map<String, Object?>> accept = _cases(corpus, 'accept');
  final List<Map<String, Object?>> reject = _cases(corpus, 'reject');

  // How many cases actually executed, checked at the end against the counts
  // above. Guards the failure mode where a `group` is accidentally skipped or
  // a filter is left in place: the totals would still be right, but nothing
  // would have run.
  int acceptRun = 0;
  int rejectRun = 0;
  final Set<String> reasonsExercised = <String>{};
  final Set<String> layersExercised = <String>{};

  group('the corpus itself', () {
    test('is the schema this file reads', () {
      expect(corpus['version'], _schemaVersion);
      expect(
        corpus['generator'],
        'cargo test -p duet-protocol --test wire_corpus -- --ignored '
        'regenerate_corpus',
        reason: 'the command that regenerates the file must stay accurate',
      );
    });

    test('has the expected number of cases', () {
      expect(accept, hasLength(_acceptCaseCount));
      expect(reject, hasLength(_rejectCaseCount));
    });

    test('names every case uniquely and hierarchically', () {
      // A failure has to name itself unambiguously. Mirrors
      // crates/duet-protocol/tests/corpus/check.rs's `check_names_unique`.
      final Set<String> seen = <String>{};
      for (final Map<String, Object?> c in <Map<String, Object?>>[
        ...accept,
        ...reject,
      ]) {
        final String name = _text(c, 'name');
        expect(name, contains('/'), reason: '$name must be hierarchical');
        expect(seen.add(name), isTrue, reason: 'duplicate case name $name');
      }
    });

    test('exercises every layer and both re-encode polarities', () {
      // The coverage floor, mirroring the Rust side's
      // `the_corpus_covers_every_reason_and_every_layer`. Without it a corpus
      // that lost half its cases would still pass everything else here.
      expect(
        accept.map((Map<String, Object?> c) => _text(c, 'layer')).toSet(),
        <String>{'value', 'request', 'response', 'push'},
      );
      expect(
        accept
            .map((Map<String, Object?> c) => c['reencode_byte_exact'])
            .toSet(),
        <bool>{true, false},
      );
      expect(
        accept.any((Map<String, Object?> c) => c['reencodes_to'] != null),
        isTrue,
        reason: 'at least one case must pin where the decoder is wider than '
            'the encoder',
      );
      expect(
        reject.map((Map<String, Object?> c) => _text(c, 'reason')).toSet(),
        containsAll(DuetReason.all),
        reason: 'every rejection reason the wire can produce must appear',
      );
    });
  });

  group('accept', () {
    for (final Map<String, Object?> c in accept) {
      final String name = _text(c, 'name');
      final String layer = _text(c, 'layer');
      final String wire = _text(c, 'wire');
      final bool byteExact = c['reencode_byte_exact']! as bool;
      final String target = (c['reencodes_to'] as String?) ?? wire;
      final Object? expectedWitness = c['witness'];

      test(name, () {
        final _Decoded decoded = _decodeAtLayer(layer, wire);

        // Built from the decoded value, never by re-reading `wire`.
        expect(
          decoded.witness,
          equals(expectedWitness, _matcherRecursionLimit),
          reason: '$name decoded to the wrong value',
        );

        if (byteExact) {
          // Byte equality is a fair demand only when the canonical encoding
          // holds no JSON-number float payload, because float *rendering*
          // legitimately differs between languages (`1e16` in Rust,
          // `10000000000000000.0` in Dart) while denoting the same double.
          // Rust computes the flag; this side just obeys it.
          expect(
            decoded.reencoded,
            target,
            reason: '$name re-encoded to the wrong bytes',
          );
        } else {
          expect(
            _normalizeJson(decodeDuetJson(decoded.reencoded)),
            equals(_normalizeJson(decodeDuetJson(target)),
                _matcherRecursionLimit),
            reason: '$name re-encoded to a structurally different document',
          );
        }

        layersExercised.add(layer);
        acceptRun++;
      });
    }
  });

  group('reject', () {
    for (final Map<String, Object?> c in reject) {
      final String name = _text(c, 'name');
      final String layer = _text(c, 'layer');
      final String wire = _text(c, 'wire');
      final String reason = _text(c, 'reason');

      test('$name ($reason)', () {
        Object? decoded;
        Object? thrown;
        try {
          decoded = _decodeAtLayer(layer, wire).witness;
        } catch (e) {
          // Deliberately `catch (e)` and not `on DuetException`: the assertion
          // is that NOTHING else escapes. A raw FormatException from
          // dart:convert, a TypeError from an unchecked cast or a RangeError
          // from a substring would all be caught here and then fail the type
          // check below, naming what leaked.
          thrown = e;
        }
        expect(
          thrown,
          isNotNull,
          reason: '$name must be rejected, but decoded to $decoded',
        );
        expect(
          thrown,
          isA<DuetCodecException>(),
          reason: '$name must be refused by this package, not by whatever is '
              'underneath it — got ${thrown.runtimeType}: $thrown',
        );
        // The reason is the point. Asserting only "is an error" is close to
        // asserting nothing: a codec mutated anywhere still refuses every
        // reject case, each one for a new and wrong reason.
        expect(
          (thrown! as DuetCodecException).reason,
          reason,
          reason: '$name was rejected for the wrong reason ($thrown)',
        );

        reasonsExercised.add(reason);
        rejectRun++;
      });
    }
  });

  tearDownAll(() {
    expect(
      acceptRun,
      _acceptCaseCount,
      reason: 'every accept case must actually have run',
    );
    expect(
      rejectRun,
      _rejectCaseCount,
      reason: 'every reject case must actually have run',
    );
    expect(layersExercised, <String>{'value', 'request', 'response', 'push'});
    expect(reasonsExercised, containsAll(DuetReason.all));
  });
}

/// A decoded case: what it decoded to, expressed as a witness, and what it
/// re-encodes to.
class _Decoded {
  const _Decoded(this.witness, this.reencoded);

  /// The witness built from the decoded value.
  final Object? witness;

  /// The canonical wire text the decoded value re-encodes to.
  final String reencoded;
}

/// Decodes [wire] with the decoder the corpus addresses it to.
_Decoded _decodeAtLayer(String layer, String wire) => switch (layer) {
      'value' => _decodedValue(DuetValue.fromWireText(wire)),
      'request' => _decodedRequest(DuetRequest.fromWireText(wire)),
      'response' => _decodedResponse(DuetResponse.fromWireText(wire)),
      'push' => _decodedPush(DuetPush.fromWireText(wire)),
      _ => throw ArgumentError.value(layer, 'layer', 'unknown corpus layer'),
    };

_Decoded _decodedValue(DuetValue v) =>
    _Decoded(_valueWitness(v), v.toWireText());

_Decoded _decodedRequest(DuetRequest r) =>
    _Decoded(_requestWitness(r), r.toWireText());

_Decoded _decodedResponse(DuetResponse r) =>
    _Decoded(_responseWitness(r), r.toWireText());

_Decoded _decodedPush(DuetPush p) => _Decoded(_pushWitness(p), p.toWireText());

/// The witness for a decoded [DuetValue].
///
/// Mirrors crates/duet-protocol/tests/corpus/witness.rs's `value`.
Object? _valueWitness(DuetValue v) => switch (v) {
      DuetNull() => <String, Object?>{'k': 'null'},
      DuetBool(:final bool value) => <String, Object?>{'k': 'bool', 'v': value},
      // A decimal string, so an i64 past 2^53 stays exact in a JavaScript reader —
      // the same reason the wire itself carries ints as strings.
      DuetInt(:final int value) => <String, Object?>{
          'k': 'int',
          'v': value.toString(),
        },
      DuetFloat(:final double value) => <String, Object?>{
          'k': 'float',
          'bits': _floatBits(value),
        },
      DuetStr(:final String value) => <String, Object?>{
          'k': 'str',
          'utf8': utf8.encode(value).toList(),
        },
      DuetBytes(:final List<int> value) => <String, Object?>{
          'k': 'bytes',
          'hex': _hex(value),
        },
      DuetList(:final List<DuetValue> items) => <String, Object?>{
          'k': 'list',
          'items': <Object?>[
            for (final DuetValue item in items) _valueWitness(item)
          ],
        },
      // Pinned as an ORDERED array rather than a JSON object, because it is the
      // key order that is under test and no JSON parser is obliged to preserve an
      // object's. Rust's BTreeMap iterates in UTF-8 byte order, which is exactly
      // code-point order — hence compareDuetMapKeys and not String.compareTo.
      DuetMap(:final Map<String, DuetValue> entries) => <String, Object?>{
          'k': 'map',
          'entries': <Object?>[
            for (final String key
                in entries.keys.toList(growable: false)
                  ..sort(compareDuetMapKeys))
              <Object?>[key, _valueWitness(entries[key]!)],
          ],
        },
    };

/// The witness for an optional value: JSON `null` means the path was absent,
/// deliberately distinct from `{"k":"null"}`.
Object? _optionalWitness(DuetValue? v) => v == null ? null : _valueWitness(v);

/// The witness for a decoded [DuetRequest].
Object? _requestWitness(DuetRequest r) => switch (r) {
      DuetGetRequest(:final DuetPath path) => <String, Object?>{
          'k': 'get',
          'id': r.id.toString(),
          'path': path.toString(),
        },
      DuetSetRequest(:final DuetPath path, :final DuetValue value) =>
        <String, Object?>{
          'k': 'set',
          'id': r.id.toString(),
          'path': path.toString(),
          'value': _valueWitness(value),
        },
      DuetSubscribeRequest(:final DuetPath path) => <String, Object?>{
          'k': 'subscribe',
          'id': r.id.toString(),
          'path': path.toString(),
        },
      DuetUnsubscribeRequest(:final int subscription) => <String, Object?>{
          'k': 'unsubscribe',
          'id': r.id.toString(),
          'subscription': subscription.toString(),
        },
    };

/// The witness for a decoded [DuetResponse].
Object? _responseWitness(DuetResponse r) => switch (r) {
      DuetValueResponse(:final DuetValue? value) => <String, Object?>{
          'k': 'value',
          'id': r.id.toString(),
          'value': _optionalWitness(value),
        },
      DuetDoneResponse() => <String, Object?>{
          'k': 'done',
          'id': r.id.toString()
        },
      DuetSubscribedResponse(
        :final int subscription,
        :final DuetValue? snapshot,
      ) =>
        <String, Object?>{
          'k': 'subscribed',
          'id': r.id.toString(),
          'subscription': subscription.toString(),
          'snapshot': _optionalWitness(snapshot),
        },
      // The failure message is a guest-visible string, so it gets the same
      // UTF-8-bytes treatment as any other string.
      DuetFailedResponse(:final String message) => <String, Object?>{
          'k': 'failed',
          'id': r.id.toString(),
          'message': _valueWitness(DuetStr(message)),
        },
    };

/// The witness for a decoded [DuetPush].
Object? _pushWitness(DuetPush p) => switch (p) {
      DuetNotificationPush(:final DuetNotification notification) =>
        <String, Object?>{
          'k': 'notification',
          'subscriber': notification.subscriber.toString(),
          'subscription': notification.subscription.toString(),
          'path': notification.path.toString(),
          'value': _valueWitness(notification.value),
        },
    };

/// The IEEE-754 bits of [v] as 16 lowercase hex characters.
///
/// Bits, never decimal text: float rendering is not comparable across
/// languages. Bits also make the comparison *stricter than `==`* — `NaN`
/// matches `NaN` (which `==` does not), and `-0.0` does not match `0.0` (which
/// `==` does), so a decoder that dropped the sign bit cannot pass.
///
/// Read as two unsigned 32-bit halves rather than one 64-bit word: Dart's
/// `int` is signed, so `getUint64` cannot represent a pattern with the sign
/// bit set — every negative float would come back as a negative integer and
/// render with a `-`.
String _floatBits(double v) {
  final ByteData bytes = ByteData(8)..setFloat64(0, v);
  return bytes.getUint32(0).toRadixString(16).padLeft(8, '0') +
      bytes.getUint32(4).toRadixString(16).padLeft(8, '0');
}

/// Lowercase hex, two characters per byte.
String _hex(List<int> bytes) => <String>[
      for (final int b in bytes) b.toRadixString(16).padLeft(2, '0'),
    ].join();

/// Replaces every `double` in a parsed JSON tree with its bit pattern, so a
/// structural comparison cannot be fooled the way `==` can.
///
/// Without this, the fallback comparison for non-byte-exact cases would treat
/// `-0.0` and `0.0` as the same document and every `NaN` as unequal to itself.
Object? _normalizeJson(Object? json) => switch (json) {
      final double d => 'double:${_floatBits(d)}',
      final List<Object?> items => <Object?>[
          for (final Object? item in items) _normalizeJson(item),
        ],
      final Map<String, Object?> map => <String, Object?>{
          for (final MapEntry<String, Object?> e in map.entries)
            e.key: _normalizeJson(e.value),
        },
      _ => json,
    };

/// Reads and parses the committed corpus.
Map<String, Object?> _loadCorpus() {
  final File file = File(_corpusPath);
  if (!file.existsSync()) {
    throw StateError(
      'cannot find the wire corpus at $_corpusPath (working directory '
      '${Directory.current.path}). It is generated by the Rust workspace with:'
      '\n    cargo test -p duet-protocol --test wire_corpus -- --ignored '
      'regenerate_corpus',
    );
  }
  return jsonDecode(file.readAsStringSync())! as Map<String, Object?>;
}

/// Reads one of the corpus's case arrays.
List<Map<String, Object?>> _cases(Map<String, Object?> corpus, String field) {
  final Object? raw = corpus[field];
  if (raw is! List<Object?>) {
    throw StateError('the corpus is missing the "$field" array');
  }
  return <Map<String, Object?>>[
    for (final Object? c in raw) c! as Map<String, Object?>,
  ];
}

/// Reads a required string field from a case object.
String _text(Map<String, Object?> c, String field) {
  final Object? raw = c[field];
  if (raw is! String) {
    throw StateError('a corpus case is missing a string "$field": $c');
  }
  return raw;
}
