/// Reading `corpus/schema-corpus.json`.
///
/// The corpus is generated by the Rust workspace
/// (`cargo test -p duet-codegen --test schema_corpus -- --ignored
/// regenerate_corpus`) and consumed as a peer by every guest. It lives outside
/// every language's tree because none of them owns it.
///
/// Two files here read it, for two different reasons:
///
/// - `schema_corpus_test.dart` checks the **generated codecs** against it with
///   no host at all: the wire keys each struct occupies, the values each field
///   admits, the values each field must refuse, and the seed walked by path.
/// - `live_host_test.dart` uses it as the *input* to a run against the real
///   host: which paths exist, what to write at each, and what a store holds
///   before anything is written.
///
/// One reader, so the two cannot disagree about what the file says.
library;

import 'dart:convert';
import 'dart:io';

import 'package:duet/duet.dart';

/// Where the corpus lives, relative to this package's root — which is the
/// working directory `dart test` runs in.
const String corpusPath = '../../corpus/schema-corpus.json';

/// The schema version this file knows how to read.
const int schemaCorpusVersion = 1;

/// The command that regenerates the corpus, named in every diagnostic.
const String corpusGenerator =
    'cargo test -p duet-codegen --test schema_corpus -- --ignored '
    'regenerate_corpus';

/// One field of one schema type.
final class CorpusField {
  /// Reads a field entry.
  CorpusField(Map<String, Object?> json)
      : key = _text(json, 'key'),
        ty = _text(json, 'ty'),
        optional = _flag(json, 'optional'),
        accept = DuetValue.fromWireText(_text(json, 'accept')),
        rejects = _wires(json, 'rejects');

  /// The wire key this field occupies in its struct's map.
  final String key;

  /// How the corpus spells this field's type.
  final String ty;

  /// True when the field is an `Option<T>`.
  final bool optional;

  /// A value the field's type admits.
  final DuetValue accept;

  /// Values the field's type must refuse. Empty only for `dynamic`.
  final List<DuetValue> rejects;
}

/// One path a generated client binds.
final class CorpusPath {
  /// Reads a path entry.
  CorpusPath(Map<String, Object?> json)
      : path = _text(json, 'path'),
        ty = _text(json, 'ty'),
        optional = _flag(json, 'optional'),
        seed = _optionalWire(json, 'seed'),
        accept = DuetValue.fromWireText(_text(json, 'accept')),
        rejects = _wires(json, 'rejects');

  /// The whole wire path from the store's root; `''` at the root.
  final String path;

  /// How the corpus spells the type at this path.
  final String ty;

  /// True when the path holds an `Option<T>`.
  final bool optional;

  /// What a seeded store holds here, or null when nothing is here at all.
  ///
  /// Null is **not** [DuetNull]: it means the path addresses no node, which is
  /// the state every path below a `None` struct is in. The wire spells the
  /// other one `{"t":"n"}`.
  final DuetValue? seed;

  /// A value the type at this path admits.
  final DuetValue accept;

  /// Values the type at this path must refuse.
  final List<DuetValue> rejects;
}

/// One schema's whole entry.
final class CorpusSchema {
  /// Reads a schema entry.
  CorpusSchema(Map<String, Object?> json)
      : name = _text(json, 'name'),
        source = _text(json, 'source'),
        root = _text(json, 'root'),
        seed = DuetValue.fromWireText(_text(json, 'seed')),
        types = <String, List<CorpusField>>{
          for (final Map<String, Object?> type in _objects(json, 'types'))
            _text(type, 'name'): <CorpusField>[
              for (final Map<String, Object?> field in _objects(type, 'fields'))
                CorpusField(field),
            ],
        },
        paths = <CorpusPath>[
          for (final Map<String, Object?> path in _objects(json, 'paths'))
            CorpusPath(path),
        ];

  /// The fixture name: what `duet-host-stdio` is started with.
  final String name;

  /// The schema file this was generated from.
  final String source;

  /// The root type's name.
  final String root;

  /// What a store holds before anything is written.
  final DuetValue seed;

  /// Every struct, by name, with its fields in declaration order.
  final Map<String, List<CorpusField>> types;

  /// Every path a generated client binds, ordered by path.
  final List<CorpusPath> paths;

  /// The entry for [path].
  CorpusPath at(String path) => paths.firstWhere(
        (CorpusPath p) => p.path == path,
        orElse: () => throw StateError('the corpus has no path "$path"'),
      );
}

/// The whole corpus.
final class SchemaCorpus {
  /// Reads and parses the committed corpus.
  factory SchemaCorpus.load() {
    final File file = File(corpusPath);
    if (!file.existsSync()) {
      throw StateError(
        'cannot find the schema corpus at $corpusPath (working directory '
        '${Directory.current.path}). It is generated by the Rust workspace '
        'with:\n    $corpusGenerator',
      );
    }
    final Object? decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map<String, Object?>) {
      throw StateError('the schema corpus is not a JSON object');
    }
    return SchemaCorpus._(decoded);
  }

  SchemaCorpus._(Map<String, Object?> json)
      : version = json['version']! as int,
        generator = _text(json, 'generator'),
        schemas = <String, CorpusSchema>{
          for (final Map<String, Object?> schema in _objects(json, 'schemas'))
            _text(schema, 'name'): CorpusSchema(schema),
        };

  /// The corpus format version.
  final int version;

  /// The command that regenerates it.
  final String generator;

  /// Every schema, by fixture name.
  final Map<String, CorpusSchema> schemas;

  /// The entry for the fixture named [name].
  CorpusSchema operator [](String name) =>
      schemas[name] ??
      (throw StateError('the corpus has no schema "$name"'));
}

/// Reads a required string field.
String _text(Map<String, Object?> json, String field) {
  final Object? raw = json[field];
  if (raw is! String) {
    throw StateError('a corpus entry is missing a string "$field": $json');
  }
  return raw;
}

/// Reads a required boolean field.
bool _flag(Map<String, Object?> json, String field) {
  final Object? raw = json[field];
  if (raw is! bool) {
    throw StateError('a corpus entry is missing a boolean "$field": $json');
  }
  return raw;
}

/// Reads a required array of objects.
List<Map<String, Object?>> _objects(Map<String, Object?> json, String field) {
  final Object? raw = json[field];
  if (raw is! List<Object?>) {
    throw StateError('a corpus entry is missing an array "$field": $json');
  }
  return <Map<String, Object?>>[
    for (final Object? entry in raw) entry! as Map<String, Object?>,
  ];
}

/// Reads a required array of wire strings, decoding each.
List<DuetValue> _wires(Map<String, Object?> json, String field) {
  final Object? raw = json[field];
  if (raw is! List<Object?>) {
    throw StateError('a corpus entry is missing an array "$field": $json');
  }
  return <DuetValue>[
    for (final Object? entry in raw) DuetValue.fromWireText(entry! as String),
  ];
}

/// Reads a wire string that may be JSON null, meaning "no node here".
DuetValue? _optionalWire(Map<String, Object?> json, String field) {
  final Object? raw = json[field];
  if (raw == null) return null;
  if (raw is! String) {
    throw StateError('a corpus entry has a non-string "$field": $json');
  }
  return DuetValue.fromWireText(raw);
}
