/// The Duet wire protocol in pure Dart.
///
/// Duet is a Rust host that owns shared state, with guests — a Flutter engine,
/// a `wry` webview — reading and writing it over a tagged-JSON protocol. This
/// package is the Dart half of that protocol, and it depends on nothing but
/// `dart:convert`.
///
/// Three layers, each usable on its own:
///
/// - [DuetValue] and friends: the value tree and its tagged-JSON codec, the
///   mirror of `duet_core::Value` and `duet-codec`.
/// - [DuetRequest], [DuetResponse] and [DuetPush]: the message envelope, the
///   mirror of `duet-protocol`.
/// - [DuetClient]: the guest API — `get`, `set`, `subscribe`, `unsubscribe`
///   and pushes — over a [DuetTransport] the caller supplies.
///
/// # Why the transport is a parameter
///
/// The only thing a Flutter guest needs beyond this package is a
/// `BasicMessageChannel`, and the Flutter `services.dart` library that defines
/// it cannot even be *loaded* under `dart test` — it is a compile error, not a
/// lint, because `dart:ui` does not exist off-device. Putting the transport
/// behind an
/// interface keeps the entire wire format testable with the plain Dart SDK,
/// which is what lets CI verify it against the cross-language golden corpus in
/// seconds. `duet_flutter` supplies the one small adapter.
///
/// # Conformance
///
/// `test/wire_corpus_test.dart` runs this package against
/// `corpus/wire-corpus.json`, the golden wire corpus generated by the Rust
/// workspace and consumed as a peer by every implementation. Every accept case
/// is decoded, compared against a witness written in a deliberately *different*
/// representation, and re-encoded; every reject case must be refused, for the
/// recorded reason.
library;

export 'src/duet_client.dart';
export 'src/duet_error.dart';
export 'src/duet_json.dart'
    show
        compareDuetMapKeys,
        decodeDuetJson,
        encodeDuetJson,
        isCanonicalSignedDecimal,
        isCanonicalUnsignedDigits,
        sortedJsonObject;
export 'src/duet_message.dart';
export 'src/duet_path.dart';
export 'src/duet_transport.dart';
export 'src/duet_value.dart';
