/**
 * Conformance against the cross-language golden wire corpus.
 *
 * `corpus/wire-corpus.json` is generated by the Rust workspace
 * (`cargo test -p duet-protocol --test wire_corpus -- --ignored
 * regenerate_corpus`) and consumed as a peer by every implementation of the
 * format. It lives outside every language's tree because none of them owns it.
 *
 * Four cross-language divergences have already been found and fixed in this
 * project, none of which a single-language round-trip test could see:
 * non-canonical ids causing a silent hang, `-0.0` losing its sign in
 * JavaScript, an id domain wider in Rust than Dart can represent, and map key
 * order differing between UTF-8 bytes and UTF-16 code units. This file is what
 * stops the next one.
 *
 * # Why the witness is not just the wire JSON again
 *
 * If the expectation were JSON of the same shape as the wire, this file could
 * satisfy every accept case by parsing the wire text and echoing it back —
 * never exercising a decoder at all. Every witness below is therefore built
 * **from the decoded value**, in a deliberately different representation:
 * floats as IEEE-754 bits in hex, strings as UTF-8 byte arrays, maps as ordered
 * entry arrays. See crates/duet-protocol/tests/corpus/witness.rs.
 *
 * @module
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { after, describe, test } from 'node:test';

import {
  compareDuetMapKeys,
  decodeDuetJson,
  decodePushText,
  decodeRequestText,
  decodeResponseText,
  decodeValueText,
  DuetCodecError,
  DUET_REASONS,
  encodePushText,
  encodeRequestText,
  encodeResponseText,
  encodeValueText,
  formatDuetPath,
  type DuetPush,
  type DuetRequest,
  type DuetResponse,
  type DuetValue,
} from '../src/index.ts';

/**
 * Where the corpus lives, resolved from this file rather than from the working
 * directory, so `npm test` behaves the same whichever directory it is run from.
 */
const CORPUS_URL = new URL('../../../corpus/wire-corpus.json', import.meta.url);

/** The schema version this file knows how to read. */
const SCHEMA_VERSION = 1;

/** The command that regenerates the corpus, pinned so it cannot go stale. */
const GENERATOR = 'cargo test -p duet-protocol --test wire_corpus -- --ignored regenerate_corpus';

/**
 * The case counts the corpus must contain.
 *
 * Pinned as literals on purpose. A corpus test that silently consumes whatever
 * it is given is worthless: a file truncated to one case would pass every
 * assertion below and prove nothing. If these numbers need changing, that is a
 * deliberate review step.
 */
const ACCEPT_CASE_COUNT = 50;
const REJECT_CASE_COUNT = 20;

interface AcceptCase {
  readonly layer: string;
  readonly name: string;
  readonly wire: string;
  readonly witness: unknown;
  readonly reencode_byte_exact: boolean;
  readonly reencodes_to: string | null;
}

interface RejectCase {
  readonly layer: string;
  readonly name: string;
  readonly wire: string;
  readonly reason: string;
}

const corpus = JSON.parse(readFileSync(CORPUS_URL, 'utf8')) as {
  version: number;
  generator: string;
  accept: AcceptCase[];
  reject: RejectCase[];
};

// How many cases actually executed, checked at the end against the counts
// above. Guards the failure mode where a `describe` is accidentally skipped or
// a filter is left in place: the totals would still be right, but nothing would
// have run.
let acceptRun = 0;
let rejectRun = 0;
const reasonsExercised = new Set<string>();
const layersExercised = new Set<string>();

describe('the corpus itself', () => {
  test('is the schema this file reads', () => {
    assert.equal(corpus.version, SCHEMA_VERSION);
    assert.equal(
      corpus.generator,
      GENERATOR,
      'the command that regenerates the file must stay accurate',
    );
  });

  test('has the expected number of cases', () => {
    assert.equal(corpus.accept.length, ACCEPT_CASE_COUNT);
    assert.equal(corpus.reject.length, REJECT_CASE_COUNT);
  });

  test('names every case uniquely and hierarchically', () => {
    // A failure has to name itself unambiguously. Mirrors
    // crates/duet-protocol/tests/corpus/check.rs's `check_names_unique`.
    const seen = new Set<string>();
    for (const c of [...corpus.accept, ...corpus.reject]) {
      assert.ok(c.name.includes('/'), `${c.name} must be hierarchical`);
      assert.ok(!seen.has(c.name), `duplicate case name ${c.name}`);
      seen.add(c.name);
    }
  });

  test('exercises every layer and both re-encode polarities', () => {
    // The coverage floor, mirroring the Rust side's
    // `the_corpus_covers_every_reason_and_every_layer`. Without it a corpus
    // that lost half its cases would still pass everything else here.
    assert.deepStrictEqual(
      new Set(corpus.accept.map((c) => c.layer)),
      new Set(['value', 'request', 'response', 'push']),
    );
    assert.deepStrictEqual(
      new Set(corpus.accept.map((c) => c.reencode_byte_exact)),
      new Set([true, false]),
    );
    assert.ok(
      corpus.accept.some((c) => c.reencodes_to !== null),
      'at least one case must pin where the decoder is wider than the encoder',
    );
    const reasons = new Set(corpus.reject.map((c) => c.reason));
    for (const reason of DUET_REASONS) {
      assert.ok(reasons.has(reason), `no reject case exercises ${reason}`);
    }
  });
});

describe('accept', () => {
  for (const c of corpus.accept) {
    const target = c.reencodes_to ?? c.wire;

    test(c.name, () => {
      const decoded = decodeAtLayer(c.layer, c.wire);

      // Built from the decoded value, never by re-reading `wire`.
      assert.deepStrictEqual(decoded.witness, c.witness, `${c.name} decoded to the wrong value`);

      if (c.reencode_byte_exact) {
        // Byte equality is a fair demand only when the canonical encoding holds
        // no JSON-number float payload, because float *rendering* legitimately
        // differs between languages (`1e16` in Rust, `10000000000000000` in
        // JavaScript) while denoting the same double. Rust computes the flag;
        // this side just obeys it.
        assert.equal(decoded.reencoded, target, `${c.name} re-encoded to the wrong bytes`);
      } else {
        assert.deepStrictEqual(
          normalizeJson(decodeDuetJson(decoded.reencoded)),
          normalizeJson(decodeDuetJson(target)),
          `${c.name} re-encoded to a structurally different document`,
        );
      }

      layersExercised.add(c.layer);
      acceptRun++;
    });
  }
});

describe('reject', () => {
  for (const c of corpus.reject) {
    test(`${c.name} (${c.reason})`, () => {
      let decoded: unknown;
      let thrown: unknown;
      let threw = false;
      try {
        decoded = decodeAtLayer(c.layer, c.wire).witness;
      } catch (error) {
        // Deliberately catches everything, not just DuetCodecError: the
        // assertion is that NOTHING else escapes. A raw SyntaxError from
        // JSON.parse, a TypeError from an unchecked property access or a
        // RangeError from a blown stack would all be caught here and then fail
        // the type check below, naming what leaked.
        thrown = error;
        threw = true;
      }
      assert.ok(threw, `${c.name} must be rejected, but decoded to ${JSON.stringify(decoded)}`);
      assert.ok(
        thrown instanceof DuetCodecError,
        `${c.name} must be refused by this package, not by whatever is underneath it — ` +
          `got ${String(thrown)}`,
      );
      // The reason is the point. Asserting only "is an error" is close to
      // asserting nothing: a codec mutated anywhere still refuses every reject
      // case, each one for a new and wrong reason.
      assert.equal(
        (thrown as DuetCodecError).reason,
        c.reason,
        `${c.name} was rejected for the wrong reason (${String(thrown)})`,
      );

      reasonsExercised.add(c.reason);
      rejectRun++;
    });
  }
});

after(() => {
  assert.equal(acceptRun, ACCEPT_CASE_COUNT, 'every accept case must actually have run');
  assert.equal(rejectRun, REJECT_CASE_COUNT, 'every reject case must actually have run');
  assert.deepStrictEqual(layersExercised, new Set(['value', 'request', 'response', 'push']));
  for (const reason of DUET_REASONS) {
    assert.ok(reasonsExercised.has(reason), `no reject case exercised ${reason}`);
  }
});

/** A decoded case: what it decoded to, as a witness, and what it re-encodes to. */
interface Decoded {
  readonly witness: unknown;
  readonly reencoded: string;
}

/** Decodes `wire` with the decoder the corpus addresses it to. */
function decodeAtLayer(layer: string, wire: string): Decoded {
  switch (layer) {
    case 'value': {
      const v = decodeValueText(wire);
      return { witness: valueWitness(v), reencoded: encodeValueText(v) };
    }
    case 'request': {
      const r = decodeRequestText(wire);
      return { witness: requestWitness(r), reencoded: encodeRequestText(r) };
    }
    case 'response': {
      const r = decodeResponseText(wire);
      return { witness: responseWitness(r), reencoded: encodeResponseText(r) };
    }
    case 'push': {
      const p = decodePushText(wire);
      return { witness: pushWitness(p), reencoded: encodePushText(p) };
    }
    default:
      throw new Error(`unknown corpus layer ${layer}`);
  }
}

/**
 * The witness for a decoded value.
 *
 * Mirrors crates/duet-protocol/tests/corpus/witness.rs's `value`.
 */
function valueWitness(v: DuetValue): unknown {
  switch (v.kind) {
    case 'null':
      return { k: 'null' };
    case 'bool':
      return { k: 'bool', v: v.value };
    // A decimal string, so an i64 past 2^53 stays exact in a JavaScript reader —
    // the same reason the wire itself carries ints as strings.
    case 'int':
      return { k: 'int', v: v.value.toString() };
    case 'float':
      return { k: 'float', bits: floatBits(v.value) };
    case 'str':
      return { k: 'str', utf8: [...new TextEncoder().encode(v.value)] };
    case 'bytes':
      return { k: 'bytes', hex: hex(v.value) };
    case 'list':
      return { k: 'list', items: v.items.map(valueWitness) };
    // Pinned as an ORDERED array rather than a JSON object, because it is the
    // key order that is under test and no JSON parser is obliged to preserve an
    // object's — and because a JavaScript object would reorder integer-like
    // keys before the comparison ever ran. Rust's BTreeMap iterates in UTF-8
    // byte order, which is exactly code-point order — hence compareDuetMapKeys
    // and not a default sort.
    case 'map':
      return {
        k: 'map',
        entries: [...v.entries.keys()]
          .sort(compareDuetMapKeys)
          .map((key) => [key, valueWitness(v.entries.get(key) as DuetValue)]),
      };
  }
}

/**
 * The witness for an optional value: JSON `null` means the path was absent,
 * deliberately distinct from `{"k":"null"}`.
 */
function optionalWitness(v: DuetValue | null): unknown {
  return v === null ? null : valueWitness(v);
}

function requestWitness(r: DuetRequest): unknown {
  switch (r.kind) {
    case 'get':
      return { k: 'get', id: r.id.toString(), path: formatDuetPath(r.path) };
    case 'set':
      return {
        k: 'set',
        id: r.id.toString(),
        path: formatDuetPath(r.path),
        value: valueWitness(r.value),
      };
    case 'subscribe':
      return { k: 'subscribe', id: r.id.toString(), path: formatDuetPath(r.path) };
    case 'unsubscribe':
      return { k: 'unsubscribe', id: r.id.toString(), subscription: r.subscription.toString() };
  }
}

function responseWitness(r: DuetResponse): unknown {
  switch (r.kind) {
    case 'value':
      return { k: 'value', id: r.id.toString(), value: optionalWitness(r.value) };
    case 'done':
      return { k: 'done', id: r.id.toString() };
    case 'subscribed':
      return {
        k: 'subscribed',
        id: r.id.toString(),
        subscription: r.subscription.toString(),
        snapshot: optionalWitness(r.snapshot),
      };
    // The failure message is a guest-visible string, so it gets the same
    // UTF-8-bytes treatment as any other string.
    case 'failed':
      return {
        k: 'failed',
        id: r.id.toString(),
        message: valueWitness({ kind: 'str', value: r.message }),
      };
  }
}

function pushWitness(p: DuetPush): unknown {
  return {
    k: 'notification',
    subscriber: p.notification.subscriber.toString(),
    subscription: p.notification.subscription.toString(),
    path: formatDuetPath(p.notification.path),
    value: valueWitness(p.notification.value),
  };
}

/**
 * The IEEE-754 bits of `v` as 16 lowercase hex characters.
 *
 * Bits, never decimal text: float rendering is not comparable across languages.
 * Bits also make the comparison *stricter than `===`* — `NaN` matches `NaN`
 * (which `===` does not), and `-0` does not match `0` (which `===` does), so a
 * decoder that dropped the sign bit cannot pass.
 *
 * Read through `getBigUint64` rather than two 32-bit halves because JavaScript
 * has a `bigint`: the whole 64-bit pattern comes back unsigned in one read,
 * with no sign-bit contortions.
 */
function floatBits(v: number): string {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, v);
  return view.getBigUint64(0).toString(16).padStart(16, '0');
}

/** Lowercase hex, two characters per byte. */
function hex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Replaces every number in a parsed JSON tree with its bit pattern, so a
 * structural comparison cannot be fooled the way `===` can.
 *
 * Without this, the fallback comparison for non-byte-exact cases would treat
 * `-0` and `0` as the same document and every `NaN` as unequal to itself. Every
 * JSON number in this wire format is a float payload — integers travel as
 * strings — so there is nothing else this could catch by mistake.
 */
function normalizeJson(json: unknown): unknown {
  if (typeof json === 'number') return `double:${floatBits(json)}`;
  if (Array.isArray(json)) return json.map(normalizeJson);
  if (json !== null && typeof json === 'object') {
    return Object.fromEntries(
      Object.entries(json as Record<string, unknown>).map(([k, v]) => [k, normalizeJson(v)]),
    );
  }
  return json;
}
